version: '3'

services:

  mailserver:
    image: analogic/poste.io
    container_name: mailserver-softwareofsouth
    restart: always
    network_mode: "host"
    expose:
      - "25"
      - "8080"
      - "4443"
      - "110"
      - "143"
      - "465"
      - "587"
      - "993"
      - "995"
    environment:
      - TZ=America/Buenos_Aires
      - h=south.software 
      - HTTP_PORT=8080 # move port https for use of page
      - HTTPS_PORT=4443 # move port https for use of page
      - DISABLE_CLAMAV=TRUE # antivirus disable 
    volumes:
      - /mnt/mail:/data
